import Head from 'next/head';
import {
  FriendForm, FormFields, FieldType, FriendFormValues,
} from '@/components/FriendForm';
import Checkbox from '@/components/Checkbox';

const formFields: FormFields = [
  {
    name: 'requiredField',
    label: 'Required field',
    type: FieldType.TEXT,
    required: true,
  },
  {
    name: 'woogaField',
    label: 'Wooga field',
    type: FieldType.TEXT,
    required: true,
    validate: (value) => {
      if (!value.startsWith('wooga.name')) {
        return 'Not a valid name!';
      }
    },
  },
  {
    name: 'conditionalField',
    label: 'Conditional field',
    type: FieldType.TEXT,
    required: true,
    visible: (values) => (values.woogaField?.startsWith('wooga.name')),
  },
  {
    name: 'optionalField',
    label: 'Optional field',
    type: FieldType.TEXT,
    required: false,
  },
  {
    name: 'placeholderField',
    label: 'Placeholder field',
    placeholder: 'This is a placeholder text.',
    type: FieldType.TEXT,
    required: true,
  },
  {
    name: 'readOnlyField',
    label: 'Read-only',
    type: FieldType.TEXT,
    required: false,
    readOnly: true,
  },
  {
    name: 'checkboxField',
    label: 'Custom Checkbox',
    type: 'customCheckbox',
  },
];

const Home: React.FC = () => {
  const handleSubmit = (values: FriendFormValues) => new Promise<void>((resolve) => {
    setTimeout(() => {
      // eslint-disable-next-line no-alert
      alert(JSON.stringify(values, null, 2));
      resolve();
    }, 500);
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FriendForm
        fields={formFields}
        initialValues={{ readOnlyField: 'You can\'t change this' }}
        customFields={{ customCheckbox: Checkbox }}
        onSubmit={handleSubmit}
      />
    </>
  );
};

export default Home;
